### ISSUE TITLE
API 호출 로직 변경

### ISSUE THREAD

**Issue by heesong66** [champkim/mosaic_ex#22]
현재 전체 page 데이터를 가져와 페이지번호를 클릭시 저장되어있는 데이터를 그려주는데,
다른 사람이 해당 페이지 수정하면 또 다른 사람 페이지와 동기화가 안되는 이슈가 있어
버튼 클릭시 데이터를 가져오는 로직으로 변경

**Comment by champkim** [comment]
문제 있는 부분 champKim 이 수정하여 완료
