### ISSUE TITLE
페이지 구조 작성 

### ISSUE THREAD

**Issue by champkim** [champkim/mosaic_ex#3]
아래 그림과 같이 컴포넌트를 배치 하고 디자인 합니다
<br>
제외항목: Theme:컴포넌트, Window 창은 작성 하지 않습니다.
<br>
참고사이트 : https://nomcopter.github.io/react-mosaic/
<br> 

![image](https://user-images.githubusercontent.com/107668292/185275780-a23630f5-54ca-4d60-a6a3-e7a9ee5c2272.png)

**Comment by heesong66** [comment]
<App>
  <TopBar/>
  <Mosaic>
    <Panel>
      <PanelTopBar/>
    </Panel>
  </Mosaic>
</App>

**Comment by heesong66** [comment]
- [ ] height 100%
- [ ] key props로 panel에 넘겨 렌더링
- [ ] css topbar, button등 미세한 수정

**Comment by champkim** [comment]
확인 완료 했습니다.
